rm(list=ls())
gc()
source("Reproject&Resample/FUNCTION_parallel_bird_5km.R")
library(parallel)
cl <- makeCluster(16)
parLapply(cl,c(101:300),Reproject_resample)
stopCluster(cl)

rm(list=ls())
gc()
source("Reproject&Resample/FUNCTION_parallel_bird_5km.R")
library(parallel)
cl <- makeCluster(31)
parLapply(cl,c(301:800),Reproject_resample)
stopCluster(cl)