rm(list=ls())
gc()
sppa <- read.csv("Stats/SPList_PAcoverage.csv")
summary(sppa$PAselect)
nrow(sppa[sppa$PAselect>=sppa$target&sppa$category%in%c("VU","EN","CR"),])/nrow(sppa[sppa$category%in%c("VU","EN","CR"),])
nrow(sppa[sppa$PAselect>=sppa$target&sppa$taxa=="mammal"&sppa$category%in%c("VU","EN","CR"),])/nrow(sppa[sppa$taxa=="mammal"&sppa$category%in%c("VU","EN","CR"),])
nrow(sppa[sppa$PAselect>=sppa$target&sppa$taxa=="bird"&sppa$category%in%c("VU","EN","CR"),])/nrow(sppa[sppa$taxa=="bird"&sppa$category%in%c("VU","EN","CR"),])
nrow(sppa[sppa$PAselect>=sppa$target&sppa$taxa=="reptile"&sppa$category%in%c("VU","EN","CR"),])/nrow(sppa[sppa$taxa=="reptile"&sppa$category%in%c("VU","EN","CR"),])
nrow(sppa[sppa$PAselect>=sppa$target&sppa$taxa=="amphibian"&sppa$category%in%c("VU","EN","CR"),])/nrow(sppa[sppa$taxa=="amphibian"&sppa$category%in%c("VU","EN","CR"),])
